# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/16305/Downloads/othello-project-sohinithota

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/16305/Downloads/othello-project-sohinithota

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/16305/Downloads/othello-project-sohinithota/CMakeFiles /mnt/c/Users/16305/Downloads/othello-project-sohinithota/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/16305/Downloads/othello-project-sohinithota/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named othello_tests

# Build rule for target.
othello_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 othello_tests
.PHONY : othello_tests

# fast build rule for target.
othello_tests/fast:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/build
.PHONY : othello_tests/fast

#=============================================================================
# Target rules for targets named othello_demo

# Build rule for target.
othello_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 othello_demo
.PHONY : othello_demo

# fast build rule for target.
othello_demo/fast:
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/build
.PHONY : othello_demo/fast

othello.o: othello.c.o

.PHONY : othello.o

# target to build an object file
othello.c.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello.c.o
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello.c.o
.PHONY : othello.c.o

othello.i: othello.c.i

.PHONY : othello.i

# target to preprocess a source file
othello.c.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello.c.i
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello.c.i
.PHONY : othello.c.i

othello.s: othello.c.s

.PHONY : othello.s

# target to generate assembly for a file
othello.c.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello.c.s
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello.c.s
.PHONY : othello.c.s

othello_demo.o: othello_demo.c.o

.PHONY : othello_demo.o

# target to build an object file
othello_demo.c.o:
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello_demo.c.o
.PHONY : othello_demo.c.o

othello_demo.i: othello_demo.c.i

.PHONY : othello_demo.i

# target to preprocess a source file
othello_demo.c.i:
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello_demo.c.i
.PHONY : othello_demo.c.i

othello_demo.s: othello_demo.c.s

.PHONY : othello_demo.s

# target to generate assembly for a file
othello_demo.c.s:
	$(MAKE) -f CMakeFiles/othello_demo.dir/build.make CMakeFiles/othello_demo.dir/othello_demo.c.s
.PHONY : othello_demo.c.s

othello_tests.o: othello_tests.cc.o

.PHONY : othello_tests.o

# target to build an object file
othello_tests.cc.o:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.o
.PHONY : othello_tests.cc.o

othello_tests.i: othello_tests.cc.i

.PHONY : othello_tests.i

# target to preprocess a source file
othello_tests.cc.i:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.i
.PHONY : othello_tests.cc.i

othello_tests.s: othello_tests.cc.s

.PHONY : othello_tests.s

# target to generate assembly for a file
othello_tests.cc.s:
	$(MAKE) -f CMakeFiles/othello_tests.dir/build.make CMakeFiles/othello_tests.dir/othello_tests.cc.s
.PHONY : othello_tests.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... othello_tests"
	@echo "... othello_demo"
	@echo "... othello.o"
	@echo "... othello.i"
	@echo "... othello.s"
	@echo "... othello_demo.o"
	@echo "... othello_demo.i"
	@echo "... othello_demo.s"
	@echo "... othello_tests.o"
	@echo "... othello_tests.i"
	@echo "... othello_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

